name: homeassistant

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      majors:
      count:
  schedule:
    - cron: "0 0 * * *"

jobs:
  get-release:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.release.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Handle workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "majors=${{ github.event.inputs.majors }}" >> $GITHUB_ENV
          echo "count=${{ github.event.inputs.count }}" >> $GITHUB_ENV

      - name: Grab latest release tag
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          json=$(deno run --allow-net --allow-env homeassistant/get-release.ts)
          echo "matrix=$json" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: [get-release]
    strategy:
      matrix: ${{ fromJSON(needs.get-release.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./homeassistant/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/homeassistant-hacs:${{ matrix.tag }}

  repository:
    runs-on: ubuntu-latest
    needs: [latest]

    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/homeassistant-hacs
          readme-filepath: ./homeassistant-hacs/README.md
          enable-url-completion: true
          short-description: "Homeassistant and Hacs bundled together"
